trainer: basic
output_dir: $SCRATCH/pytorch-benchmarks/alexnet

data_config:
    name: dummy
    n_train: 1024
    n_valid: 1024
    input_shape: [3, 224, 224]
    n_classes: 1000

model_config:
    model_type: alexnet
    num_classes: 1000
    optimizer: 'Adam'
    learning_rate: 0.001

train_config:
    batch_size: 128
    n_epochs: 1
