data_config:
    name: cifar10
    data_path: $SCRATCH/pytorch-cifar10/data
    n_train: 16384
    n_valid: 10000

experiment_config:
    name: cifar10
    output_dir: $SCRATCH/pytorch-cifar10/output

train_config:
    batch_size: 128
    n_epochs: 1
