trainer: basic
output_dir: $SCRATCH/pytorch-benchmarks/${BENCHMARK_VERSION}/cnn3d

data_config:
    name: dummy
    n_train: 1024
    n_valid: 1024
    input_shape: [1, 32, 32, 32]
    n_classes: 4
    batch_size: 64

model_config:
    model_type: cnn3d
    input_shape: [1, 32, 32, 32]
    output_size: 4
    optimizer: 'Adam'
    learning_rate: 0.001

train_config:
    n_epochs: 1
