trainer: generic
output_dir: $BENCHMARK_RESULTS_PATH/lstm

data_config:
    name: dummy
    n_train: 2048
    n_valid: 2048
    input_shape: [50, 500] # (seq_size, input_size)
    n_classes: 4
    batch_size: 64
    use_dist_sampler_train: false
    use_dist_sampler_valid: false

model_config:
    model_type: lstm
    input_size: 500
    hidden_size: 500
    output_size: 4
    optimizer: 'Adam'
    learning_rate: 0.001

train_config:
    n_epochs: 8
