trainer: basic
output_dir: $BENCHMARK_RESULTS_PATH/vgg11

data_config:
    name: dummy
    n_train: 2048
    n_valid: 2048
    input_shape: [3, 224, 224]
    n_classes: 1000
    batch_size: 128

model_config:
    model_type: vgg11
    num_classes: 1000
    optimizer: 'Adam'
    learning_rate: 0.001

train_config:
    n_epochs: 1
